# Generated by Django 5.1.1 on 2024-09-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='socials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
