# Generated by Django 5.1.1 on 2024-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_radioshow_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioshow',
            name='genre_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='radioshow',
            name='genre_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='radioshow',
            name='genre_3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
