# Generated by Django 5.1.1 on 2024-10-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_radioshow_genre_1_alter_radioshow_genre_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioshow',
            old_name='genre_1',
            new_name='genre1',
        ),
        migrations.RenameField(
            model_name='radioshow',
            old_name='genre_2',
            new_name='genre2',
        ),
        migrations.RenameField(
            model_name='radioshow',
            old_name='genre_3',
            new_name='genre3',
        ),
    ]
