# Generated by Django 4.2.7 on 2025-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_genre_1_radioshow_genre1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='show_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
