# Generated by Django 4.2.7 on 2025-03-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_radioshow_show_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioshow',
            old_name='show_image',
            new_name='show_image_url',
        ),
    ]
