# Generated by Django 4.2.7 on 2025-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_show_image_radioshow_show_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioshow',
            old_name='show_image_url',
            new_name='show_image',
        ),
    ]
