# Generated by Django 4.2.7 on 2025-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_show_image_url_radioshow_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
