# Generated by Django 4.2.7 on 2025-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_radioshow_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='pre_record',
            field=models.URLField(blank=True, null=True),
        ),
    ]
